#!/bin/sh

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
REMOTE_BRANCH=$(git ls-remote origin | grep -w $CURRENT_BRANCH)
LAST_COMMIT=$(git rev-parse --short HEAD)
LAST_COMMIT_GO_FILES=$(git diff-tree --no-commit-id --name-only -r $LAST_COMMIT | grep .go)

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)

# If there are no go files to push, then exit
if [ -z "$LAST_COMMIT_GO_FILES" ]; then
  exit 0
fi

make test
if [[ $? != 0 ]]; then
  printf "${RED}Tests failed! ${NORMAL}Please fix tests before pushing.\n"
  exit 1
else
 printf "${GREEN}Tests passed! ${NORMAL}Continuing to push.\n"
 exit 0
fi